let express = require('express');
let router = express.Router();
let controller = require('../controllers/UserController');
router.post('/register', controller.register);
router.get('/', controller.getAll);
router.get('/:id', controller.getById);
router.delete('/:id', controller.deleteById);
router.put('/:id', controller.updateById);
router.post('/login', controller.login);
module.exports = router;